### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by cox890** [jima80525/mp3splitter#2]
a guide on how to use this tool would be useful. i want to split overdrive mp3 file than convert to m4b with https://github.com/sandreas/m4b-tool

**Comment by jima80525** [comment]
I've added a small section on usage (and status). Is that what you were looking for?  Frankly, the m4b-tool looks like it might be a superset of this tool.   What's the workflow you're trying to achieve?

**Comment by cox890** [comment]
i was hoping it would split the mp3 file in chapter in original folder or create a text file containing chapter mark that i could use to create m4b file using m4b-tool

**Comment by welpdx** [comment]
Hi @ink79, the m4b-tool looks interesting but it looks like it has many dependencies. Jim's script here can split and do same things (split mp3 files based on chapter) with less hassle, albeit with less features. 

If you need help to split overdrive mp3 files using this script. I'm sure one of us can give you a hand. But since neither of us are that familiar with m4b-tool, I don't think we would be much help in producing a text file for m4b.

**Comment by cox890** [comment]
thanks for the replay m4b-tool now support overdrive mp3 file and export as a single chaptalized m4b file, so i no longer need it.
